stages:
  - linux
  - macos
  - composer
  - reproduce
  - coverage
  - deploy

default:
  before_script:
    - mkdir -p "/tmp/jobs"
    - ./.gitlab-ci.d/travis/clean.sh 'all'
    - if [ ! -d "/tmp/jobs/$(date +%j)" ]; then rm -fr "/tmp/jobs/*"; mkdir -p "/tmp/$(date +%j)"; fi
  after_script:
    - if [ -f /tmp/jobs/$(date +%j)/${CI_CONCURRENT_ID}_${CI_CONCURRENT_PROJECT_ID} ]; then bash /tmp/jobs/$(date +%j)/${CI_CONCURRENT_ID}_${CI_CONCURRENT_PROJECT_ID}; fi
    - rm -fr /tmp/jobs/$(date +%j)/${CI_CONCURRENT_ID}_${CI_CONCURRENT_PROJECT_ID}

perform_reproduce_issues:
  stage: reproduce
  script:
    - if [[ ${#TASK} -gt 0 ]] && [ $TASK != 'reproduce' ]; then exit 0; fi
    - if [[ ${#TOKEN} -eq 0 ]]; then exit 0; fi
    - ./.gitlab-ci.d/travis/reproduce.sh ${REPRODUCES}
  tags:
    - Travis
  allow_failure: true

build_with_travis:
  stage: linux
  script:
    - if [[ ${#TASK} -gt 0 ]] && [ $TASK != 'build' ]; then exit 0; fi
    - if [[ ${#TOKEN} -eq 0 ]]; then exit 0; fi
    - ./.gitlab-ci.d/travis/build.sh ${BUILDS}
  tags:
    - Travis
  allow_failure: true

build_kernel_linux:
  stage: linux
  script:
    - if [[ ${#TASK} -gt 0 ]] && [ $TASK != 'kernel' ]; then exit 0; fi
    - if [[ ${#TOKEN} -eq 0 ]]; then exit 0; fi
    - ./.gitlab-ci.d/travis/kernel.sh ${KERNELS}
  tags:
    - Travis
  when: manual
 
build_with_macos_7.3:
  stage: macos
  script:
    - if [[ ${#TASK} -gt 0 ]] && [ $TASK != 'macos' ]; then exit 0; fi
    - if [[ ${#TOKEN} -eq 0 ]]; then exit 0; fi
    - ./.gitlab-ci.d/travis/build.sh 8
  tags:
    - Travis
  allow_failure: true

build_with_macos_8.3:
  stage: macos
  script:
    - if [[ ${#TASK} -gt 0 ]] && [ $TASK != 'macos' ]; then exit 0; fi
    - if [[ ${#TOKEN} -eq 0 ]]; then exit 0; fi
    - ./.gitlab-ci.d/travis/build.sh 9
  tags:
    - Travis
  allow_failure: true

build_with_macos_9.1:
  stage: macos
  script:
    - if [[ ${#TASK} -gt 0 ]] && [ $TASK != 'macos' ]; then exit 0; fi
    - if [[ ${#TOKEN} -eq 0 ]]; then exit 0; fi
    - ./.gitlab-ci.d/travis/build.sh 11
  tags:
    - Travis
  allow_failure: true

build_with_macos_9.2:
  stage: macos
  script:
    - if [[ ${#TASK} -gt 0 ]] && [ $TASK != 'macos' ]; then exit 0; fi
    - if [[ ${#TOKEN} -eq 0 ]]; then exit 0; fi
    - ./.gitlab-ci.d/travis/build.sh 12
  tags:
    - Travis
  allow_failure: true

build_with_macos_9.3:
  stage: macos
  script:
    - if [[ ${#TASK} -gt 0 ]] && [ $TASK != 'macos' ]; then exit 0; fi
    - if [[ ${#TOKEN} -eq 0 ]]; then exit 0; fi
    - ./.gitlab-ci.d/travis/build.sh 13
  tags:
    - Travis
  allow_failure: true

pages:
  stage: deploy
  dependencies:
    - perform_reproduce_issues
    - build_with_travis
    - build_with_macos_7.3
    - build_with_macos_8.3
    - build_with_macos_9.1
    - build_with_macos_9.2
    - build_with_macos_9.3
  script:
    - mkdir -p public
    - if [ -d ./Coverages ]; then cp -a ./Coverages public; fi
    - if [ -d ./Logs ]; then cp -a ./Logs public; fi
    - if [ -n "$(find public -maxdepth 0 -type d -empty 2>/dev/null)" ]; then touch public/.lock; fi
  tags:
    - Travis
  artifacts:
    paths:
      - public
    expire_in: 2 days
