stages:
  - test
  - deploy

default:

perform_testing_on_linux:
  stage: test
  script:
    - if [[ ${#TASK} -gt 0 ]] && [ $TASK != 'build' ]; then exit 0; fi
    - if [[ ${#WERCKER} -eq 0 ]]; then exit 0; fi
    - ./Tests/Pipeline/Enqueue.sh $(pwd)/.gitlab-ci.d/build.sh -- --labs ${LINUX} --os linux
  after_script:
    - ./Tests/Pipeline/Enqueue.sh ./gitlab-ci.d/build.sh --cleanup
  tags:
    - Yggdrasil
  allow_failure: true

perform_reproducing_on_linux:
  stage: test
  script:
    - if [[ ${#TASK} -gt 0 ]] && [ $TASK != 'build' ]; then exit 0; fi
    - if [[ ${#WERCKER} -eq 0 ]]; then exit 0; fi
    - ./Tests/Pipeline/Enqueue.sh $(pwd)/.gitlab-ci.d/reproduce.sh -- --labs ${LINUX} --os linux
  after_script:
    - ./Tests/Pipeline/Enqueue.sh ./gitlab-ci.d/reproduce.sh --cleanup
  tags:
    - Yggdrasil
  allow_failure: true
