stages:
  - linux
  - macos
  - composer
  - reproduce
  - coverage
  - deploy

perform_reproduce_issues:
  stage: reproduce
  script:
    - if [[ ${#TASK} -gt 0 ]] && [ $TASK != 'reproduce' ]; then exit 0; fi
    - if [[ ${#TOKEN} -eq 0 ]]; then exit 0; fi
    - ./.gitlab-ci.d/travis/reproduce.sh ${REPRODUCES}
  tags:
    - Travis
  allow_failure: true

build_with_travis:
  stage: linux
  script:
    - if [[ ${#TASK} -gt 0 ]] && [ $TASK != 'build' ]; then exit 0; fi
    - if [[ ${#TOKEN} -eq 0 ]]; then exit 0; fi
    - ./.gitlab-ci.d/travis/build.sh ${BUILDS}
  tags:
    - Travis
  allow_failure: true

build_kernel_linux:
  stage: linux
  script:
    - if [[ ${#TASK} -gt 0 ]] && [ $TASK != 'kernel' ]; then exit 0; fi
    - if [[ ${#TOKEN} -eq 0 ]]; then exit 0; fi
    - ./.gitlab-ci.d/travis/kernel.sh ${KERNELS}
  tags:
    - Travis
  when: manual
 
build_with_macos_7.3:
  stage: macos
  script:
    - if [[ ${#TASK} -gt 0 ]] && [ $TASK != 'macos' ]; then exit 0; fi
    - if [[ ${#TOKEN} -eq 0 ]]; then exit 0; fi
    - ./Tools/Utilities/travis.sh restart --job 8 --patch ${PATCH} --token ${TOKEN} --repo ${REPO}
  tags:
    - Travis
  allow_failure: true

build_with_macos_8.3:
  stage: macos
  script:
    - if [[ ${#TASK} -gt 0 ]] && [ $TASK != 'macos' ]; then exit 0; fi
    - if [[ ${#TOKEN} -eq 0 ]]; then exit 0; fi
    - ./Tools/Utilities/travis.sh restart --job 9 --patch ${PATCH} --token ${TOKEN} --repo ${REPO}
  tags:
    - Travis
  allow_failure: true

build_with_macos_9.1:
  stage: macos
  script:
    - if [[ ${#TASK} -gt 0 ]] && [ $TASK != 'macos' ]; then exit 0; fi
    - if [[ ${#TOKEN} -eq 0 ]]; then exit 0; fi
    - ./Tools/Utilities/travis.sh restart --job 11 --patch ${PATCH} --token ${TOKEN} --repo ${REPO}
  tags:
    - Travis
  allow_failure: true

build_with_macos_9.2:
  stage: macos
  script:
    - if [[ ${#TASK} -gt 0 ]] && [ $TASK != 'macos' ]; then exit 0; fi
    - if [[ ${#TOKEN} -eq 0 ]]; then exit 0; fi
    - ./Tools/Utilities/travis.sh restart --job 12 --patch ${PATCH} --token ${TOKEN} --repo ${REPO}
  tags:
    - Travis
  allow_failure: true

build_with_macos_9.3:
  stage: macos
  script:
    - if [[ ${#TASK} -gt 0 ]] && [ $TASK != 'macos' ]; then exit 0; fi
    - if [[ ${#TOKEN} -eq 0 ]]; then exit 0; fi
    - ./Tools/Utilities/travis.sh restart --job 13 --patch ${PATCH} --token ${TOKEN} --repo ${REPO}
  tags:
    - Travis
  allow_failure: true

pages:
  stage: deploy
  dependencies:
    - perform_reproduce_issues
    - build_with_travis
    - build_with_macos_7.3
    - build_with_macos_8.3
    - build_with_macos_9.1
    - build_with_macos_9.2
    - build_with_macos_9.3
  script:
    - mkdir -p public
    - if [ -d ./Coverages ]; then cp -a ./Coverages public; fi
    - if [ -d ./Logs ]; then cp -a ./Logs public; fi
    - if [ -n "$(find public -maxdepth 0 -type d -empty 2>/dev/null)" ]; then touch public/.lock; fi
  tags:
    - Travis
  artifacts:
    paths:
      - public
    expire_in: 2 days
