stages:
  - test
  - deploy
  - status

perform_testing_on_linux:
  stage: test
  script:
    - if [[ ${#TASK} -gt 0 ]] && [ $TASK != 'build' ]; then exit 0; fi
    - if [[ ${#WERCKER} -eq 0 ]]; then exit 0; fi
    - ./Tests/Pipeline/Enqueue.sh $(pwd)/.gitlab-ci.d/build.sh -- --labs ${LINUX} --os linux
  after_script:
    - ./Tests/Pipeline/Enqueue.sh ./.gitlab-ci.d/build.sh --cleanup
  tags:
    - Yggdrasil

perform_reproducing_on_linux:
  stage: test
  script:
    - if [[ ${#TASK} -gt 0 ]] && [ $TASK != 'build' ]; then exit 0; fi
    - if [[ ${#WERCKER} -eq 0 ]]; then exit 0; fi
    - ./Tests/Pipeline/Enqueue.sh $(pwd)/.gitlab-ci.d/reproduce.sh -- --labs ${LINUX} --os linux
  after_script:
    - ./Tests/Pipeline/Enqueue.sh ./.gitlab-ci.d/reproduce.sh --cleanup
  tags:
    - Yggdrasil

success:
  stage: status
  before_script:
    - ""
  after_script:
    - ""
  script:
    - BUILD_STATUS=passed BUILD_KEY=push ./.gitlab-ci.d/bitbucket-status.sh
  when: on_success
  tags:
    - Yggdrasil

failure:
  stage: status
  before_script:
    - ""
  after_script:
    - ""
  script:
    - BUILD_STATUS=failed BUILD_KEY=push ./.gitlab-ci.d/bitbucket-status.sh
  when: on_failure
  tags:
    - Yggdrasil
