#ifndef BASE_CONFIG_H_
#define BASE_CONFIG_H_

/** @NOTE: this file is generated by application only, the repository Base
 * doesn't write anything here, i put this file here to help whoever want to use
 * this repository better.
 * 
 * - By default, each application should default this file to control the Base
 * libraries better since we might face so many different configuration from
 * each application
 * - The libraries should refer to the unique USE_BASE_WITH_FULL_PATH_HEADER.
 * This macro help our libraries to know how to deal with headers better. The
 * reason why i need to care about it because we are facing two kind of
 * including headers into application, one way is similar to XCode usually does,
 * use shortname only. Another is the way the Bazel usually use, full path
 * headers. These ways are very hard to deal so i need this macro to be defined
 * whenever you want to use the full-path headers, by default i support the
 * other since i'm working on OSX mainly and i don't want this config cause any
 * trouble to my applications.
 *
 * */
#endif  // BASE_CONFIG_H_
